name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifier le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurer Java (ici, Java 8, mais tu peux ajuster la version)
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'

      # 3. Installer les dépendances et compiler le projet avec Maven
      - name: Build with Maven
        run: mvn clean package --file pom.xml

      # 4. (Optionnel) Télécharger le .jar généré en tant qu'artefact
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app-jar
          path: target/*.jar
