name: Build and Deploy

on:
  push:
    branches:
      - main # Déclenche sur les commits dans la branche main
  pull_request:
    branches:
      - main # Déclenche sur les pull requests vers la branche main

permissions:
  contents: write
  actions: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest # Machine virtuelle Ubuntu

    steps:
      # 1. Vérifier le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurer Java (version 8)
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "1.8"

      # 3. Installer les dépendances et construire avec Maven
      - name: Build with Maven
        run: mvn clean package --file pom.xml

      # 4. Télécharger le fichier .jar généré
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v1 # Utilisation de la version 1
        with:
          name: my-app-jar
          path: target/*.jar
